import type { Token, Deployer, Event } from './types';

// Generate mock tokens
export const MOCK_TOKENS: Token[] = [
    {
        id: '1',
        symbol: '$BAGS',
        name: 'BAGS Protocol',
        deployer_wallet: '0x7a3...f2e1',
        launch_time: Date.now() - 86400000 * 2,
        launch_score: 92,
        status: 'live',
        insider_pct: 8,
        dev_sold: false,
        dev_pct: 5,
        retail_pct: 87,
        volume_24h: 2400000,
        market_cap: 12500000,
        holders: 3420,
        funding_type: 'fresh',
    },
    {
        id: '2',
        symbol: '$ALPHA',
        name: 'Alpha Terminal',
        deployer_wallet: '0x3b2...a4c8',
        launch_time: Date.now() - 86400000 * 5,
        launch_score: 85,
        status: 'live',
        insider_pct: 12,
        dev_sold: false,
        dev_pct: 8,
        retail_pct: 80,
        volume_24h: 890000,
        market_cap: 4200000,
        holders: 1892,
        funding_type: 'fresh',
    },
    {
        id: '3',
        symbol: '$DEGEN',
        name: 'Degen Finance',
        deployer_wallet: '0x9c4...b3d2',
        launch_time: Date.now() - 3600000 * 12,
        launch_score: 67,
        status: 'new',
        insider_pct: 28,
        dev_sold: false,
        dev_pct: 15,
        retail_pct: 57,
        volume_24h: 560000,
        market_cap: 980000,
        holders: 456,
        funding_type: 'recycled',
    },
    {
        id: '4',
        symbol: '$RUG',
        name: 'Rugged Token',
        deployer_wallet: '0x1d5...e9f3',
        launch_time: Date.now() - 86400000 * 10,
        launch_score: 12,
        status: 'rugged',
        insider_pct: 65,
        dev_sold: true,
        dev_pct: 45,
        retail_pct: 0,
        volume_24h: 0,
        market_cap: 0,
        holders: 234,
        funding_type: 'suspicious',
    },
    {
        id: '5',
        symbol: '$WHALE',
        name: 'Whale Protocol',
        deployer_wallet: '0x7a3...f2e1',
        launch_time: Date.now() - 86400000 * 1,
        launch_score: 78,
        status: 'live',
        insider_pct: 18,
        dev_sold: false,
        dev_pct: 10,
        retail_pct: 72,
        volume_24h: 1200000,
        market_cap: 3800000,
        holders: 987,
        funding_type: 'fresh',
    },
    {
        id: '6',
        symbol: '$STEALTH',
        name: 'Stealth Launch',
        deployer_wallet: '0x2e6...c1a4',
        launch_time: Date.now() - 3600000 * 2,
        launch_score: 54,
        status: 'stealth',
        insider_pct: 35,
        dev_sold: false,
        dev_pct: 20,
        retail_pct: 45,
        volume_24h: 89000,
        market_cap: 120000,
        holders: 78,
        funding_type: 'recycled',
    },
    {
        id: '7',
        symbol: '$GRAD',
        name: 'Graduate Token',
        deployer_wallet: '0x3b2...a4c8',
        launch_time: Date.now() - 86400000 * 30,
        launch_score: 95,
        status: 'graduated',
        insider_pct: 5,
        dev_sold: false,
        dev_pct: 3,
        retail_pct: 92,
        volume_24h: 5600000,
        market_cap: 45000000,
        holders: 12450,
        funding_type: 'fresh',
    },
    {
        id: '8',
        symbol: '$PUMP',
        name: 'Pump Token',
        deployer_wallet: '0x8f1...d2b5',
        launch_time: Date.now() - 3600000 * 6,
        launch_score: 42,
        status: 'new',
        insider_pct: 45,
        dev_sold: false,
        dev_pct: 25,
        retail_pct: 30,
        volume_24h: 340000,
        market_cap: 450000,
        holders: 234,
        funding_type: 'suspicious',
    },
];

// Generate mock deployers
export const MOCK_DEPLOYERS: Deployer[] = [
    {
        wallet: '0x7a3...f2e1',
        name: 'whale_deployer',
        total_launches: 12,
        success_rate: 83,
        avg_score: 78,
        risk_flags: [],
        last_launch: Date.now() - 86400000,
        total_volume: 45000000,
        insider_usage_avg: 12,
    },
    {
        wallet: '0x3b2...a4c8',
        name: 'alpha_builder',
        total_launches: 8,
        success_rate: 75,
        avg_score: 82,
        risk_flags: [],
        last_launch: Date.now() - 86400000 * 5,
        total_volume: 28000000,
        insider_usage_avg: 8,
    },
    {
        wallet: '0x9c4...b3d2',
        name: 'degen_dev',
        total_launches: 24,
        success_rate: 42,
        avg_score: 51,
        risk_flags: ['high_insider_avg', 'recycled_wallets'],
        last_launch: Date.now() - 3600000 * 12,
        total_volume: 8900000,
        insider_usage_avg: 35,
    },
    {
        wallet: '0x1d5...e9f3',
        name: 'rugger_anon',
        total_launches: 6,
        success_rate: 0,
        avg_score: 15,
        risk_flags: ['serial_rugger', 'dev_sold_all', 'suspicious_funding'],
        last_launch: Date.now() - 86400000 * 10,
        total_volume: 450000,
        insider_usage_avg: 68,
    },
    {
        wallet: '0x2e6...c1a4',
        name: 'stealth_launcher',
        total_launches: 3,
        success_rate: 33,
        avg_score: 48,
        risk_flags: ['new_wallet'],
        last_launch: Date.now() - 3600000 * 2,
        total_volume: 560000,
        insider_usage_avg: 28,
    },
];

// Generate mock events
export const MOCK_EVENTS: Event[] = [
    {
        id: '1',
        type: 'launch',
        severity: 'info',
        related_token: '$STEALTH',
        related_deployer: '0x2e6...c1a4',
        timestamp: Date.now() - 3600000 * 2,
        title: 'New Stealth Launch',
        description: 'stealth_launcher deployed $STEALTH with 35% insider allocation',
    },
    {
        id: '2',
        type: 'whale_entry',
        severity: 'success',
        related_token: '$BAGS',
        timestamp: Date.now() - 3600000 * 4,
        title: 'Whale Entry Detected',
        description: '0x7b2...3a1f bought $42K of $BAGS',
    },
    {
        id: '3',
        type: 'alert',
        severity: 'warning',
        related_token: '$PUMP',
        related_deployer: '0x8f1...d2b5',
        timestamp: Date.now() - 3600000 * 6,
        title: 'High Insider Concentration',
        description: '$PUMP showing 45% insider allocation - elevated risk',
    },
    {
        id: '4',
        type: 'rug',
        severity: 'critical',
        related_token: '$RUG',
        related_deployer: '0x1d5...e9f3',
        timestamp: Date.now() - 86400000 * 10,
        title: 'Rug Pull Confirmed',
        description: 'rugger_anon sold 100% of dev allocation on $RUG',
    },
    {
        id: '5',
        type: 'funding',
        severity: 'warning',
        related_deployer: '0x9c4...b3d2',
        timestamp: Date.now() - 3600000 * 8,
        title: 'Recycled Funding Detected',
        description: 'degen_dev used previously linked wallets for new launch',
    },
    {
        id: '6',
        type: 'distribution',
        severity: 'success',
        related_token: '$GRAD',
        timestamp: Date.now() - 86400000 * 2,
        title: 'Healthy Distribution',
        description: '$GRAD reached 92% retail distribution - graduated',
    },
];

// Helper to get deployer by wallet
export const getDeployerByWallet = (wallet: string): Deployer | undefined => {
    return MOCK_DEPLOYERS.find(d => d.wallet === wallet);
};

// Helper to get tokens by deployer
export const getTokensByDeployer = (wallet: string): Token[] => {
    return MOCK_TOKENS.filter(t => t.deployer_wallet === wallet);
};
